[tool.poetry]
name = "iscc-playground"
version = "0.1.0"
description = "UI for ISCC exploration"
authors = ["Titusz <tp@py7.de>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
gradio = "^4.12.0"
iscc-sdk = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
