name: Sync with Hugging Face Hub
on:
  push:
    branches:
      - main
jobs:
  sync:
    name: Sync to Hugging Face Spaces
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Sync to Hugging Face Spaces
      uses: JacobLinCool/huggingface-sync@v1
      with:
        github: ${{ secrets.GITHUB_TOKEN }}
        user: iscc
        space: iscc-playground
        token: ${{ secrets.HF_TOKEN }}
