name: Sync with Hugging Face Hub
on:
  push:
    branches:
      - main
jobs:
  sync:
    name: Sync to Hugging Face Spaces
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false  # Don't use LFS on GitHub side
        
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      
    - name: Generate requirements.txt
      run: |
        uv pip compile pyproject.toml -o requirements.txt --python-platform x86_64-manylinux_2_28
        
    - name: Push to Hugging Face with LFS
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Configure git globally
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global init.defaultBranch main
        
        # Clone the Hugging Face space with LFS
        git lfs install
        git clone https://iscc:$HF_TOKEN@huggingface.co/spaces/iscc/iscc-playground hf-space || {
          echo "Clone failed, creating new repo"
          mkdir hf-space
          cd hf-space
          git init
          git lfs install
          git remote add origin https://iscc:$HF_TOKEN@huggingface.co/spaces/iscc/iscc-playground
          cd ..
        }
        
        # Remove all files in HF space except .git
        cd hf-space
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
        cd ..
        
        # Copy all files from GitHub to HF space
        rsync -av --exclude='.git' --exclude='hf-space' --exclude='.github' . hf-space/
        
        # Setup LFS tracking and commit everything
        cd hf-space
        git lfs track "*.jpg" "*.jpeg" "*.png" "*.gif" "*.bmp" "*.webp"
        git add -A
        git status
        git commit -m "Sync from GitHub: ${{ github.sha }}" || echo "No changes to commit"
        git push origin main --force-with-lease || git push origin main --force
